// import Footer from "@/components/Footer/Footer";
// import "./globals.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
{
  /* <h1>GAMES</h1> */
}
{
  /* {children} */
}
{
  /* <Footer /> */
}
{
  /* </body>
    </html>
  );
} */
}
